apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-sleeper
  labels:
    app: ubuntu-sleeper
spec:
  containers:
    - name: ubuntu-sleeper
      image: busybox
      securityContext:
        runAsUser: 1001
        capabilities:
          add: ["SYS_ADMIN"]
